// Code generated by MockGen. DO NOT EDIT.
// Source: dispatcher.go

package kim

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	pkt "github.com/klintcheng/kim/wire/pkt"
)

type MockDispatcher struct {
	ctrl     *gomock.Controller
	recorder *MockDispatcherMockRecorder
}

type MockDispatcherMockRecorder struct {
	mock *MockDispatcher
}

func NewMockDispatcher(ctrl *gomock.Controller) *MockDispatcher {
	mock := &MockDispatcher{ctrl: ctrl}
	mock.recorder = &MockDispatcherMockRecorder{mock}
	return mock
}

func (m *MockDispatcher) EXPECT() *MockDispatcherMockRecorder {
	return m.recorder
}

func (m *MockDispatcher) Push(ctx context.Context, gateway string, channels []string, p *pkt.LogicPkt) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Push", ctx, gateway, channels, p)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockDispatcherMockRecorder) Push(ctx, gateway, channels, p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Push", reflect.TypeOf((*MockDispatcher)(nil).Push), ctx, gateway, channels, p)
}
