services:
  router:
    image: docker.io/dockerklint/kim_router:v1.1
    container_name: router
    restart: always
    networks: 
      - kimnet
    ports:
      - "8100:8100"
    environment:
      KIM_CONSULURL: consul:8500
      KIM_LOGLEVEL: INFO
      KIM_KAFKA_ENABLE: "false"
      KIM_KAFKA_BROKERS: "broker-1:19092 broker-2:19092 broker-3:19092"
      KIM_KAFKA_TOPIC: kim_logs
      KIM_KAFKA_REPLICATIONFACTOR: "3"
      KIM_KAFKA_PARTITIONS: "3"
  royal:
    image: docker.io/dockerklint/kim_royal:v1.4
    container_name: royal
    restart: always
    networks: 
      - kimnet
    ports:
      - "8080:8080"
    environment:
      KIM_PUBLICADDRESS: royal
      KIM_CONSULURL: consul:8500
      KIM_REDISADDRS: redis:6379
      KIM_BASEDB: kim_user:user123@tcp(mariadb:3306)/kim_base?charset=utf8mb4&parseTime=True&loc=Local
      KIM_MESSAGEDB: kim_user:user123@tcp(mariadb:3306)/kim_message?charset=utf8mb4&parseTime=True&loc=Local
      KIM_LOGLEVEL: DEBUG
      KIM_KAFKA_ENABLE: "false"
      KIM_KAFKA_BROKERS: "broker-1:19092 broker-2:19092 broker-3:19092"
      KIM_KAFKA_TOPIC: kim_logs
      KIM_KAFKA_REPLICATIONFACTOR: "3"
      KIM_KAFKA_PARTITIONS: "3"
  gateway:
    image: docker.io/dockerklint/kim_gateway:v1.4
    container_name: wgateway
    restart: always
    networks: 
      - kimnet
    ports:
      - "8000:8000"
      - "8001:8001"
    environment:
      KIM_PUBLICADDRESS: gateway
      KIM_CONSULURL: consul:8500
      KIM_LOGLEVEL: DEBUG
      KIM_TAGS: IDC:SH_ALI
      KIM_DOMAIN: ws://localhost:8000
      KIM_KAFKA_ENABLE: "false"
      KIM_KAFKA_BROKERS: "broker-1:19092 broker-2:19092 broker-3:19092"
      KIM_KAFKA_TOPIC: kim_logs
      KIM_KAFKA_REPLICATIONFACTOR: "3"
      KIM_KAFKA_PARTITIONS: "3"
  server:
    image: docker.io/dockerklint/kim_server:v1.4
    container_name: chat
    restart: always
    networks: 
      - kimnet
    ports:
      - "8005:8005"
      - "8006:8006"
    environment:
      KIM_PUBLICADDRESS: server
      KIM_CONSULURL: consul:8500
      KIM_REDISADDRS: redis:6379
      KIM_LOGLEVEL: DEBUG
      KIM_ROYALURL: http://royal:8080
      KIM_KAFKA_ENABLE: "false"
      KIM_KAFKA_BROKERS: "broker-1:19092 broker-2:19092 broker-3:19092"
      KIM_KAFKA_TOPIC: kim_logs
      KIM_KAFKA_REPLICATIONFACTOR: "3"
      KIM_KAFKA_PARTITIONS: "3"
    dns: consul
networks:
  kimnet: {}