package comet

import (
	"bytes"
	"context"

	"github.com/klintcheng/kim"
	"github.com/klintcheng/kim/gen/rpc"
	"github.com/klintcheng/kim/internal/logger"
	"github.com/klintcheng/kim/wire"
	"github.com/klintcheng/kim/wire/pkt"
)

type CometServiceImpl struct {
	rpc.UnimplementedCometServiceServer
	router *kim.Router
	pusher kim.Dispatcher
	cache  kim.SessionStorage
}

func (s *CometServiceImpl) Forward(ctx context.Context, req *rpc.ForwardReq) (*rpc.ForwardResp, error) {
	packet, err := pkt.MustReadLogicPkt(bytes.NewBuffer(req.Packet))
	if err != nil {
		return &rpc.ForwardResp{Code: 1, Message: err.Error()}, nil
	}

	var session *pkt.Session
	if packet.Command == wire.CommandLoginSignIn {
		server, _ := packet.GetMeta(wire.MetaDestServer)
		session = &pkt.Session{
			ChannelId: packet.ChannelId,
			GateId:    server.(string),
			Tags:      []string{"AutoGenerated"},
		}
	} else {
		session, err = s.cache.Get(packet.ChannelId)
		if err == kim.ErrSessionNil {
			s.respErr(context.Background(), packet, pkt.Status_SessionNotFound)
			return &rpc.ForwardResp{Code: 0}, nil
		} else if err != nil {
			s.respErr(context.Background(), packet, pkt.Status_SystemException)
			return &rpc.ForwardResp{Code: 0}, nil
		}
	}

	logger.CometLogger.Debugf("recv a message from %s %s", session, &packet.Header)
	_ = s.router.Serve(ctx, packet, s.pusher, s.cache, session)
	return &rpc.ForwardResp{Code: 0}, nil
}

func (s *CometServiceImpl) respErr(ctx context.Context, p *pkt.LogicPkt, status pkt.Status) {
	if ctx == nil {
		ctx = context.Background()
	}
	packet := pkt.NewFrom(&p.Header)
	packet.Status = status
	packet.Flag = pkt.Flag_Response
	packet.AddStringMeta(wire.MetaDestChannels, p.Header.ChannelId)

	gateway, _ := p.GetMeta(wire.MetaDestServer)
	if gateway == nil {
		return
	}
	_ = s.pusher.Push(ctx, gateway.(string), []string{p.Header.ChannelId}, packet)
}

var _ rpc.CometServiceServer = (*CometServiceImpl)(nil)
