// 文件：comet_service_impl.go
// 职责：CometService gRPC 服务实现——实现 CometService.Forward 方法，
//       接收 Gateway 转发的消息包，反序列化后通过 Router 分发到各 handler。
//
// 说明：
//   - Forward 从 req.Packet 反序列化出 *pkt.LogicPkt
//   - 登录命令从 packet Meta 构造 session；其他命令从 cache 获取 session
//   - 通过 router.Serve 分发到 handler 链处理
//   - respErr 将错误响应通过 pusher 推送回 gateway

package comet

import (
	"bytes"
	"context"

	"github.com/klintcheng/kim"
	"github.com/klintcheng/kim/gen/rpc"
	"github.com/klintcheng/kim/logger"
	"github.com/klintcheng/kim/wire"
	"github.com/klintcheng/kim/wire/pkt"
)

// CometServiceImpl CometService gRPC 服务实现
type CometServiceImpl struct {
	rpc.UnimplementedCometServiceServer
	router *kim.Router
	pusher kim.Dispatcher
	cache  kim.SessionStorage
}

// Forward 实现 CometService.Forward，接收 Gateway 转发的消息包并分发处理
func (s *CometServiceImpl) Forward(ctx context.Context, req *rpc.ForwardReq) (*rpc.ForwardResp, error) {
	packet, err := pkt.MustReadLogicPkt(bytes.NewBuffer(req.Packet))
	if err != nil {
		return &rpc.ForwardResp{Code: 1, Message: err.Error()}, nil
	}

	var session *pkt.Session
	if packet.Command == wire.CommandLoginSignIn {
		server, _ := packet.GetMeta(wire.MetaDestServer)
		session = &pkt.Session{
			ChannelId: packet.ChannelId,
			GateId:    server.(string),
			Tags:      []string{"AutoGenerated"},
		}
	} else {
		session, err = s.cache.Get(packet.ChannelId)
		if err == kim.ErrSessionNil {
			s.respErr(packet, pkt.Status_SessionNotFound)
			return &rpc.ForwardResp{Code: 0}, nil
		} else if err != nil {
			s.respErr(packet, pkt.Status_SystemException)
			return &rpc.ForwardResp{Code: 0}, nil
		}
	}

	logger.CometLogger.Debugf("recv a message from %s %s", session, &packet.Header)
	_ = s.router.Serve(packet, s.pusher, s.cache, session)
	return &rpc.ForwardResp{Code: 0}, nil
}

// respErr 向发送方回复错误响应
func (s *CometServiceImpl) respErr(p *pkt.LogicPkt, status pkt.Status) {
	packet := pkt.NewFrom(&p.Header)
	packet.Status = status
	packet.Flag = pkt.Flag_Response
	packet.AddStringMeta(wire.MetaDestChannels, p.Header.ChannelId)

	gateway, _ := p.GetMeta(wire.MetaDestServer)
	if gateway == nil {
		return
	}
	_ = s.pusher.Push(gateway.(string), []string{p.Header.ChannelId}, packet)
}

// 编译时断言：CometServiceImpl 实现 rpc.CometServiceServer 接口
var _ rpc.CometServiceServer = (*CometServiceImpl)(nil)
